AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Path Tracer Preprocessor Function
 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  PathTracerPreprocessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionName: "distributed-path-tracer-preprocessor"
      Environment:
        Variables:
          ENV: prod
          ECS_CLUSTER: PathTracerCluster-prod
          TASK_DEFINITION: path-tracer-worker-prod
          SUBNET_ID: !ImportValue PathTracer-PrivateSubnet-prod
          SECURITY_GROUP_ID: !ImportValue PathTracer-ECSSecurityGroup-prod
      Policies:
        - S3ReadPolicy:
            BucketName: "distributed-path-tracer"
        - S3WritePolicy:
            BucketName: "distributed-path-tracer"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:ListTopics
              Resource: "*"
            - Effect: Allow
              Action:
                - sns:CreateTopic
                - sns:Subscribe
                - sns:ListSubscriptionsByTopic
              Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*-distributed-scene-topic"
            - Effect: Allow
              Action:
                - sqs:CreateQueue
                - sqs:GetQueueAttributes
                - sqs:SetQueueAttributes
                - sqs:GetQueueUrl
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*-distributed-scene-worker-*"
            - Effect: Allow
              Action:
                - ecs:RunTask
              Resource: '*'
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: '*'
      FunctionUrlConfig:
        AuthType: NONE
      Events:
        Preprocess:
          Type: Api
          Properties:
            Path: /preprocess
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../path-tracer-preprocessor/preprocessor-function
      DockerTag: latest

Outputs:
  PathTracerPreprocessorFunction:
    Description: "Path Tracer Preprocessor Lambda Function ARN"
    Value: !GetAtt PathTracerPreprocessorFunction.Arn