package main

import (
	"context"
	"log"
	"net/http"

	pb "path-tracer-backend/gen/imagedata"
	"path-tracer-backend/gen/imagedata/imagedataconnect"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

type GreeterServer struct{}

func (s *GreeterServer) SayHello(
	_ context.Context,
	req *connect.Request[pb.HelloRequest],
) (*connect.Response[pb.HelloReply], error) {
	log.Printf("Received: %v", req.Msg.GetName())
	return connect.NewResponse(&pb.HelloReply{
		Message: "Hello " + req.Msg.GetName(),
	}), nil
}

func main() {
	mux := http.NewServeMux()

	// NewGreeterHandler is generated by protoc-gen-connect-go
	path, handler := imagedataconnect.NewGreeterHandler(&GreeterServer{})
	mux.Handle(path, handler)

	// h2c allows HTTP/2 without TLS — required for gRPC in development
	addr := ":8080"
	log.Printf("Server listening on %s", addr)
	if err := http.ListenAndServe(addr, h2c.NewHandler(mux, &http2.Server{})); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
